<?php

namespace SupportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RappelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RappelRepository extends EntityRepository
{
}
