modulo:
    resource: "@ModuloBundle/Controller/"
    type:     annotation
    prefix:   /

#modulo:
#    resource: "@Asubit/ModuloBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"