gfi_redmine:
    resource: "@GfiRedmineBundle/Resources/config/routing.yml"
    prefix:   /redmine

support:
    resource: "@GfiSupportBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"