<?php

namespace Gfi\SupportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
	public function findLast($limit = 5)
	{
	    return $this->getEntityManager()
        ->createQuery('SELECT t FROM GfiSupportBundle:Ticket t ORDER BY t.id DESC')
        ->setMaxResults($limit)
        ->getResult();
	}

	public function findLastByUser($limit = 5, $user)
	{
		return $this->getEntityManager()
			->createQuery('SELECT t FROM GfiSupportBundle:Ticket t WHERE t.auteur = :auteur ORDER BY t.id DESC')
			->setParameter('auteur', $user)
			->setMaxResults($limit)
			->getResult();
	}
}
