<?php

namespace ModuloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findClose($zipCode, $productId)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('ModuloBundle:Producer', 'p')
            ->innerJoin('p.products','pp')
            ->where('p.zipCode = :zip_code')
            ->andWhere('pp.id = :product_id')
            ->setParameters(['product_id' => $productId, 'zip_code' => $zipCode])
            ->getQuery()
            ->getResult();
    }
}
