<?php

namespace ModuloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TransformerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransformerRepository extends EntityRepository
{
}
